---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Redhat.yml
  when: ansible_os_family == 'Redhat'

- name: Copy Nginx configuration
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
  notify: restart nginx

- name: Copy Nginx default configuration for Wordpress
  template: src=default dest=/etc/nginx/sites-available/default
  sudo: yes
  notify: restart nginx
