---
- name: Create git user
  sudo: yes
  user: name={{ item }} shell=/bin/bash groups=wheel append=yes
  with_items: repo_user
  tags: git_access

- name: Copy .gitconfig file to user
  sudo: yes
  copy: src=.gitconfig dest=/home/{{ item }}/
  with_items: repo_user
  tags: git_access

- name: Create .ssh directory
  sudo: yes
  file: path=/home/{{ item }}/.ssh/ owner={{ item }} group={{ item }} state=directory
  with_items: repo_user
  tags: git_access

- name: Add github.com to the known_hosts file
  sudo: yes
  shell: ssh-keyscan -H github.com > /home/{{ item }}/.ssh/known_hosts
  with_items: repo_user
  tags: git_access

- name: Copy the current hosts id_rsa.pub to users home folder
  sudo: yes
  copy: "src=~/.ssh/git_repo_user.pub dest=/home/{{ item }}/.ssh/id_rsa.pub owner={{ item }} group={{ item }} mode=644"
  with_items: repo_user
  tags: git_access

- name: Copy the current hosts id_rsa to users home folder
  sudo: yes
  copy: "src=~/.ssh/git_repo_user dest=/home/{{ item }}/.ssh/id_rsa owner={{ item }} group={{ item }} mode=600"
  with_items: repo_user
  tags: git_access

- name: Ensure users owns everything
  sudo: yes
  file: path=/home/{{ item }}/.ssh/ owner={{ item }} group={{ item }} state=directory recurse=yes
  with_items: repo_user
  tags: git_access


