---
- name: Install necessary packages with Yum
  sudo: yes
  yum: name={{ item }} state=latest
  with_items:
  - vim
  - python-pip
  tags: local

- name: Copy .gitconfig file to user
  copy: "src=.gitconfig dest=/home/vagrant/"
  tags: local

- name: Add github.com to the known_hosts file
  shell: ssh-keyscan -H github.com > /home/vagrant/.ssh/known_hosts
  tags: local

- name: Ensure vagrant owns its known_hosts file
  sudo: yes
  file: path=/home/vagrant/.ssh/known_hosts owner=vagrant group=vagrant mode=0600 state=file
  tags: local

- name: Copy the current hosts id_rsa to vagrant home folder
  sudo: yes
  sudo_user: vagrant
  copy: "src=id_rsa dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=600"
  tags: local

- name: Copy the vagrant insecure_private_key to vagrant home folder
  sudo: yes
  sudo_user: vagrant
  copy: "src=~/.vagrant.d/insecure_private_key dest=/home/vagrant/.ssh/insecure_private_key owner=vagrant group=vagrant mode=600"
  tags: local

- name: Create the .aws folder
  file: path=/home/vagrant/.aws state=directory
  tags: local

- name: Copy the AWS credential file
  copy: "src=credentials dest=/home/vagrant/.aws/"
  tags: local

- name: Install AWS CLI with pip
  sudo: yes
  pip: name=awscli
  tags: local
